Karaoke:
  Collections:
    c7db86a0-ff64-4044-9be4-66dd1ef1d1c1: true # Geek
    dbcf2c22-524d-4708-99bb-601703633927: true # Asia
    efe171c0-e8a1-4d03-98c0-60ecf741ad52: true # West
    2fa2fe3f-bb56-45ee-aa38-eae60e76f224: true # Shitpost
System:
  Database:
    bundledPostgresBinary: false
    database: karaokemugen_app
    host: postgres
    password: musubi
    port: 5432
    superuser: karaokemugen_app
    superuserPassword: musubi
    username: karaokemugen_app
  Binaries:
    Player:
      Linux: mpv
    ffmpeg:
      Linux: ffmpeg
